name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - mster
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'

env:
  DOCKER_IMAGE: gonewaje/durian  # Replace with your DockerHub username and image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.image-tag }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.image-tag }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.image-tag }}
            docker stop durianpay || true && docker rm durianpay || true
            docker run -d --name durianpay -p 8080:80 ${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.image-tag }}
